name: Test

on:
  pull_request:
    types: [opened, reopened]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'  # The Go version to download (if necessary) and use.

      - name: Build consumer
        run: go build cmd/consumer/main.go

      - name: Build api
        run: go build cmd/api/main.go
